CREATE TABLE users (id SERIAL PRIMARY KEY, username TEXT UNIQUE, password TEXT, role INTEGER);

CREATE TABLE recipes (id SERIAL PRIMARY KEY, title TEXT, instructions TEXT, user_id INTEGER REFERENCES users ON DELETE CASCADE);

CREATE TABLE feedback (id SERIAL PRIMARY KEY, skill_level INTEGER, quality INTEGER,
 comment TEXT, recipe_id INTEGER REFERENCES recipes ON DELETE CASCADE, given_by INTEGER REFERENCES users ON DELETE CASCADE);

